dist: trusty
language: python

python:
  - "2.7"

install:
  - sh ckanext/query_dois/tests/bin/build.sh

services:
  - redis-server
  - postgresql

addons:
  postgresql: "9.4"

script: coverage run --source=ckanext.query_dois setup.py nosetests --ckan --with-pylons=ckanext/query_dois/tests/bin/test.ini --nologcapture --debug=ckantest,ckanext.query_dois --rednose

after_success: coveralls
